name: fedRBE
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - r-base>=4.0
  - ca-certificates
  - certifi
  - openssl
  - conda-forge::adjusttext
  - conda-forge::bottle
  - conda-forge::docker-py
  - ipykernel
  - jupyter
  - pip
  - conda-forge::jinja2
  - conda-forge::matplotlib
  - conda-forge::numpy
  - conda-forge::pandas
  - conda-forge::pyyaml
  - conda-forge::scikit-learn
  - conda-forge::scipy
  - conda-forge::seaborn
  - conda-forge::umap-learn
  - conda-forge::upsetplot
  - conda-forge::r-data.table
  - conda-forge::r-devtools
  - conda-forge::r-ggpubr
  - conda-forge::r-ggsci
  - conda-forge::r-ggtext
  - conda-forge::r-glue
  - conda-forge::r-gridextra
  - conda-forge::r-invgamma
  - conda-forge::r-irkernel
  - conda-forge::r-jsonlite
  - conda-forge::r-knitr
  - conda-forge::r-nipals
  - conda-forge::r-patchwork
  - conda-forge::r-pheatmap
  - conda-forge::r-reshape2
  - conda-forge::r-scales
  - conda-forge::r-tidyverse
  - conda-forge::r-umap
  - conda-forge::r-viridis
  - conda-forge::r-wgcna
  - bioconda::bioconductor-affy
  - bioconda::bioconductor-geoquery
  - bioconda::bioconductor-hgu133acdf
  - bioconda::bioconductor-hgu133plus2cdf
  - bioconda::bioconductor-limma
  - bioconda::bioconductor-variancepartition
  - pip:
    - FeatureCloud>=0.1.0
    - bios>=0.1.2
