name: fedRBE
channels:
  - conda-forge
  - bioconda
  - r
channel_priority: strict        # ← ensures deterministic resolution
dependencies:
  # Core
  - python=3.11                  # lock interpreter version
  - ipykernel
  - pandas
  - matplotlib
  - seaborn
  - openssl
  - certifi
  - ca-certificates

  # R stack (all pulled from conda‑forge unless overridden)
  - r-base=4.3
  - r-tidyverse
  - r-gridextra
  - r-patchwork
  - r-umap
  - r-ggsci
  - r-viridis
  - r-irkernel
  - r-reshape2
  - r-devtools
  - r-invgamma                       # from “r” channel

  # Bioconductor
  - bioconductor-limma               
  - bioconductor-variancepartition
