flimmaBatchCorrection:
  data_filename: "lab_A_protein_groups_matrix.tsv" 
    # the file containing the expression data. Must be a 2d matrix where
    # samples are given as columns and features as rows
  design_filename: lab_A_design.tsv # the file containing covariates
                                     # it is read in the following way:
                                     # pd.read_csv(design_file_path, sep=seperator, index_col=0)
  expression_file_flag: True # If true, the datafile is expected to have the samples as columns
                             # and the features as rows. If false, the datafile is expected to have
                             # the samples as rows and the features as columns.
                             # format: boolean
  index_col: "sample" # if expression_file_flag is true, the index_col is the column name of the
                      # features in the data file. If expression_file_flag is false, the index_col
                      # is the column name of the samples in the data file.
                      # if no index_col is given, the index is taken from the 0th column for
                      # expression files and generated autopmatically for standard samplesxfeatures datafiles
                      # format: str or int, int is interpreted as the column number

  covariates: ['Pyr'] # covariates in linear model. In case a design matrix is given
                      # they are expected in the design matrix, otherwise they are expected 
                      # to be features in the given data.
                      # format: list of strings
  separator: "\t" # the separator used in the annotation or data file
  design_separator: "\t" # the separator used in the design file
  normalizationMethod: "log2(x+1)" # the method used for normalization, supported:
                                   # "log2(x+1)"
  # The following options are for privacy, we recommend one of these tiers:
  # minimum privacy:
  #   smpc = False
  #   min_samples = 0
  # medium privacy, medium slowdown
  #   smpc = True
  #   min_samples = 0
  # maximum privacy, medium to high slowdown
  #   smpc = True
  #   min_samples = 5
  # generally minimum or medium privacy is enough, only when covariates are
  # potentially known privacy might become an issue
  # With min samples > 0, the program might halt depending on the given data
  smpc: True
  min_samples: 0 # In case a covariat is known to an attacker, this ensures that
                 # in each calculation, the vector of all samples of one protein
                 # and of one covariat contain at least min_samples non Zero 
                 # non NaN samples, so that results are fuzzy enough for
                 # attackers to not quess samples. 
                 # format: int

