flimmaBatchCorrection:
  batch_col: batch
  covariates:
  - D5
  - F7
  - M8
  data_filename: intensities_log_UNION.tsv
  design_filename: design.tsv
  design_separator: "\t"
  expression_file_flag: true
  index_col: rowname
  min_samples: 0
  normalizationMethod: null
  position: 2
  reference_batch: FDU_QE-HFX_4
  separator: "\t"
  smpc: true
