flimmaBatchCorrection:
  covariates:
  - CRC
  data_filename: msp_counts_norm_logmin_5C.tsv
  design_filename: design_5C.tsv
  design_separator: "\t"
  expression_file_flag: true
  index_col: 0
  min_samples: 0
  normalizationMethod: null
  separator: "\t"
  smpc: false
