flimmaBatchCorrection:
  batch_col: batch
  covariates:
  - Pyr
  data_filename: intensities_log_UNION.tsv
  design_filename: design.tsv
  design_separator: "\t"
  expression_file_flag: true
  index_col: rowname
  min_samples: 0
  normalizationMethod: null
  position: 0
  separator: "\t"
  smpc: false
